jobs:
  action:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./workflow/verify

name: Action

on:
  schedule:
    - cron: "5 0/3 * * *"
